In [24]:
import numpy as np
import sympy as sp

In [10]:
A = np.array([[1, 0, 5, 0],
              [0, 1, 0, 11],
              [0, 1, 0, 9],
              [0, 0, 2, 0]])

b = -np.array([49, 0, 0, 20])

x = np.linalg.solve(A, b)

In [17]:
x

array([16.,  0., -4.,  0.])

In [7]:
A@x

array([-47.,   0.,   0., -20.])

In [21]:
f = lambda x: 1 - 10 * x**2 + x**4

alpha = np.sqrt(2) + np.sqrt(3)

round(f(alpha))

0.0

In [14]:
A = np.array([[1, 0, 2, 0],
              [0, 1, 0, 0],
              [0, 1, 0, 8],
              [0, 0, 2, 0]])

b = -np.array([-8, 0, 0, 8])

x = np.linalg.solve(A, b)

In [18]:
x

array([16.,  0., -4.,  0.])

In [16]:
A@x

array([ 8.,  0.,  0., -8.])

In [22]:
f = lambda x: 16 - 4 * x**2 + x**4

alpha = np.sqrt(3) + 1j

round(f(alpha))

-0j

In [26]:
x = sp.Symbol('x')

roots = sp.solve(f(x), x)

for root in roots:
    display(root)

-sqrt(3) - I

-sqrt(3) + I

sqrt(3) - I

sqrt(3) + I