# Teil 1

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 0, 0, 0], [0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1]])
print(A)

[[1 0 0 0]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


In [3]:
b = np.array([-20, -4, 10, 2])
print(b)

[-20  -4  10   2]


In [4]:
x = np.linalg.solve(A, b)
print(x)

[-20. -14.   8.   2.]


In [5]:
# Probe
print(A @ x == b)

[ True  True  True  True]


# Teil 2

In [6]:
import sympy as sp

In [7]:
tau = sp.Symbol("tau")

In [103]:
A = sp.Matrix([[0,  1,  0],
               [0,  0,  1],
               [10, 5, -2]])

In [110]:
U = sp.exp(tau*A)
U = sp.simplify(U)
display(U)

Matrix([
[         (-exp(2*tau) - 10*exp(sqrt(5)*tau) + 5*sqrt(5)*exp(sqrt(5)*tau) - 4*sqrt(5)*exp(2*tau*(1 + sqrt(5))) + 9*exp(2*tau*(1 + sqrt(5))))*exp(-tau*(2 + sqrt(5)))/(-2 + sqrt(5)), sqrt(5)*sinh(sqrt(5)*tau)/5,   -sqrt(5)*exp(sqrt(5)*tau)/5 + exp(sqrt(5)*tau)/2 + sqrt(5)*exp(-sqrt(5)*tau)/5 + exp(-sqrt(5)*tau)/2 - exp(-2*tau)],
[(sqrt(5)*exp(2*tau) - 10*sqrt(5)*exp(sqrt(5)*tau) + 20*exp(sqrt(5)*tau) - 20*exp(2*tau*(1 + sqrt(5))) + 9*sqrt(5)*exp(2*tau*(1 + sqrt(5))))*exp(-tau*(2 + sqrt(5)))/(-2 + sqrt(5)),           cosh(sqrt(5)*tau), (-(2 + sqrt(5))*exp(2*tau) + 4*exp(sqrt(5)*tau) + (-2 + sqrt(5))*exp(2*tau*(1 + sqrt(5))))*exp(-tau*(2 + sqrt(5)))/2],
[        5*(-exp(2*tau) - 8*exp(sqrt(5)*tau) + 4*sqrt(5)*exp(sqrt(5)*tau) - 4*sqrt(5)*exp(2*tau*(1 + sqrt(5))) + 9*exp(2*tau*(1 + sqrt(5))))*exp(-tau*(2 + sqrt(5)))/(-2 + sqrt(5)),   sqrt(5)*sinh(sqrt(5)*tau), -sqrt(5)*exp(sqrt(5)*tau) + 5*exp(sqrt(5)*tau)/2 + sqrt(5)*exp(-sqrt(5)*tau) + 5*exp(-sqrt(5)*tau)/2 - 4*exp(-2*tau)]])

In [116]:
# Probe

u = U[0, :]
display(u)

lhs = sp.diff(u, tau, tau, tau)
lhs = sp.simplify(lhs)
rhs = 10 * u + 5 * sp.diff(u, tau) - 2 * sp.diff(u, tau, tau)
rhs = sp.simplify(rhs)
display(lhs == rhs)

lhs = 2 * sp.diff(u, tau, tau, tau) + 4 * sp.diff(u, tau, tau) - 10 * sp.diff(u, tau) - 20 * u
lhs = sp.simplify(lhs)
display(lhs)

Matrix([[(-exp(2*tau) - 10*exp(sqrt(5)*tau) + 5*sqrt(5)*exp(sqrt(5)*tau) - 4*sqrt(5)*exp(2*tau*(1 + sqrt(5))) + 9*exp(2*tau*(1 + sqrt(5))))*exp(-tau*(2 + sqrt(5)))/(-2 + sqrt(5)), sqrt(5)*sinh(sqrt(5)*tau)/5, -sqrt(5)*exp(sqrt(5)*tau)/5 + exp(sqrt(5)*tau)/2 + sqrt(5)*exp(-sqrt(5)*tau)/5 + exp(-sqrt(5)*tau)/2 - exp(-2*tau)]])

True

Matrix([[0, 0, 0]])

In [45]:
t = sp.Symbol('t')

In [118]:
y = u.subs(tau, sp.ln(t))
y = sp.simplify(y)
display(y)

Matrix([[t**(-sqrt(5) - 2)*(t**2 - 5*sqrt(5)*t**(sqrt(5)) + 10*t**(sqrt(5)) - 9*t**(2 + 2*sqrt(5)) + 4*sqrt(5)*t**(2 + 2*sqrt(5)))/(2 - sqrt(5)), sqrt(5)*sinh(sqrt(5)*log(t))/5, t**(-sqrt(5) - 2)*(t**2*(2*sqrt(5) + 5) - 10*t**(sqrt(5)) + t**(2 + 2*sqrt(5))*(5 - 2*sqrt(5)))/10]])

In [119]:
# Probe

lhs = 2 * t**3 * sp.diff(y, t, t, t) + 10 * t**2 * sp.diff(y, t, t) - 4 * t * sp.diff(y, t) - 20 * y
lhs = sp.simplify(lhs)

display(lhs)

Matrix([[0, 0, 0]])