**Aufgabe 45:**

Seien $x_1, \ldots, x_m$ paarweise verschiedene Stützstellen mit Stützwerten $y_1, \dots, y_m$. Gesucht sei ein Polynom $p \in \Pi_n$ mit $n < m − 1$, sodass $\sum_{j=0}^m |p(x_j) − y_j|^2$ minimal wird.

**a)** Zeigen Sie mit Hilfe des Satzes 5.17, dass die Lösung $p \in \Pi_n$ des Ausgleichsproblems eindeutig ist. \
**b)** Stützstellen und Stützwerte seien gegeben durch

$$ \begin{array}{c | c | c | c | c | c}
x_i & 0 &  1 & 2 & 3  & 4  & 5 \\
\hline
y_i & 3 & −4 & 6 & 17 & 34 & 55
\end{array}. $$

Berechnen Sie $p \in \Pi_2$, sodass $\sum_{j=0}^6 |p(x_j) − y_j|^2$ minimal wird. Skizzieren Sie $p$ und die dazugehörigen Stützstellen und Stützwerte.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

x = np.array([0,  1, 2,  3,  4, 5 ])
y = np.array([3, -4, 6, 17, 34, 55])

A = np.fromfunction(lambda i, j: x[i]**j, (6, 3), dtype = int)
print("A =\n", A, "\n")

lhs = A.transpose() @ A
print("lhs =\n", lhs, "\n")

rhs = A.transpose() @ y
print("rhs =\n", rhs, "\n")

z = np.linalg.solve(lhs, rhs)
print("z =\n", z, "\n")

def p(val, coeff):
    n = len(coeff)
    tmp = 0

    for i in range(n):
        tmp += coeff[i] * val**i

    return tmp

dt = 0.1
grid = np.arange(0, 5, dt)

plt.plot(grid, p(grid, z))
plt.plot(x, y)

plt.grid(linestyle = ':')
plt.show()

A =
 [[ 1  0  0]
 [ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

lhs =
 [[  6  15  55]
 [ 15  55 225]
 [ 55 225 979]] 

rhs =
 [ 111  470 2092] 

z =
 [ 1. -4.  3.] 



ValueError: operands could not be broadcast together with shapes (50,) (6,) 